/* ============================================================
   language.js  –  EN / Tamil translations
   ============================================================ */

const LANG = {
  en: {
    /* site */
    site_title:'AgriDirect — Farm to Table',
    /* nav */
    nav_home:'Home', nav_products:'Products', nav_farmers:'Farmers',
    nav_market:'Market Prices', nav_cart:'Cart',
    nav_login:'Login', nav_register:'Register',
    nav_dashboard:'Dashboard', nav_logout:'Logout',
    nav_home:'Home', nav_orders:'Orders', nav_reviews:'Reviews', nav_profile:'Profile',
    search_ph:'Search vegetables, fruits, grains…',
    /* hero */
    hero_eyebrow:'Fresh from the Farm',
    hero_h1a:'Buy Direct from', hero_h1b:'Local Farmers',
    hero_sub:'Get the freshest produce at fair prices. Support local farmers and know exactly where your food comes from.',
    hero_shop:'Shop Now', hero_farmer:"I'm a Farmer",
    hero_stat_farmers:'Farmers', hero_stat_products:'Products',
    hero_stat_orders:'Orders Fulfilled', hero_stat_cities:'Cities',
    /* categories */
    cat_heading:'Shop by Category',
    cat_all:'All', cat_vegetables:'Vegetables', cat_fruits:'Fruits',
    cat_grains:'Grains & Pulses', cat_dairy:'Dairy',
    /* products */
    featured:'Featured Products', see_all:'See All →',
    add_to_cart:'Add to Cart', added:'Added!',
    market_price:'Market Price', per_kg:'/kg', per_unit:'/unit', per_litre:'/litre',
    organic:'Organic', inorganic:'Conventional',
    harvest_date:'Harvested', in_stock:'In Stock', out_of_stock:'Out of Stock',
    available:'available',
    no_results:'No products found', no_results_sub:'Try adjusting your filters.',
    /* auth */
    login:'Login', register:'Register',
    mobile_no:'Mobile Number', otp:'Enter OTP',
    otp_sent:'OTP sent to', verify:'Verify OTP',
    resend:'Resend OTP', resend_in:'Resend in', seconds:'s',
    full_name:'Full Name', i_am_farmer:"I'm a Farmer",
    i_am_customer:"I'm a Customer",
    location:'Location / Village', farm_name:'Farm Name',
    continue_btn:'Continue',
    add_profile_photo:'Add Profile Photo',
    /* cart */
    cart_title:'Your Cart', cart_empty:'Your cart is empty',
    cart_empty_sub:'Add some fresh produce to get started!',
    subtotal:'Subtotal', delivery:'Delivery', free:'Free', total:'Total',
    go_checkout:'Proceed to Checkout',
    /* checkout */
    checkout_title:'Checkout',
    delivery_addr:'Delivery Address', delivery_method:'Delivery Method',
    payment_method:'Payment Method',
    cod:'Cash on Delivery', cod_desc:'Pay when you receive your order',
    online_pay:'Online Payment', online_desc:'UPI, Cards, Net Banking – Razorpay',
    farmer_del:'Farmer Self Delivery', local_del:'Local Delivery Partner',
    farm_pickup:'Pickup from Farm',
    place_order:'Place Order', order_success:'Order placed successfully!',
    addr_line1:'Address Line 1', addr_line2:'Address Line 2 (Optional)',
    city:'City', state:'State', pincode:'Pincode',
    /* orders */
    my_orders:'My Orders', order_id:'Order ID', order_date:'Date',
    order_status:'Status', order_total:'Total',
    track_order:'Track Order',
    status_placed:'Order Placed', status_confirmed:'Confirmed',
    status_out:'Out for Delivery', status_out_for_delivery:'Out for Delivery', status_delivered:'Delivered', status_cancelled:'Cancelled',
    method_pickup:'Farm Pickup', method_delivery:'Home Delivery',
    method_home_delivery:'Home Delivery',
    method_farmer_delivery:'Farmer Delivery', method_local_partner:'Local Delivery', method_farm_pickup:'Farm Pickup',
    /* farmer dashboard */
    dashboard:'Dashboard', my_products:'My Products',
    add_product:'Add Product', edit_product:'Edit',
    del_product:'Delete', save_product:'Save Product',
    update_product:'Update Product',
    product_name:'Product Name', category:'Category',
    price_per:'Price per kg / unit', qty:'Available Quantity',
    product_type:'Product Type', description:'Description',
    upload_imgs:'Upload Images',
    price_changed:'Price updated on',
    price_change_alert:'Price change will be logged with date & time for full transparency.',
    unit:'Unit', kg:'kg', per_unit_piece:'unit', per_bunch:'bunch', per_litre:'litre',
    click_to_upload:'Click to upload multiple images',
    drag_drop:'or drag & drop',
    img_hint:'JPG, PNG, WEBP • Max 5 images • Max 5 MB each',
    use_camera:'Use Camera',
    upload_hint:'Upload clear, well-lit photos showing freshness and quality',
    farmer_support:'Farmer Support',
    tn_gov_schemes:'TN Government Schemes & Support',
    scheme_electricity:'Free Electricity for Agricultural Pumps',
    scheme_electricity_desc:'Farmers in Tamil Nadu receive free electricity for irrigation pumpsets used in agriculture.',
    scheme_electricity_i1:'Electricity for farm pumps is free.',
    scheme_electricity_i2:'New connections are issued based on infrastructure availability.',
    scheme_electricity_i3:'Solar pump users may have different rules for new free connections.',
    scheme_machinery:'Agricultural Machinery Subsidy',
    scheme_machinery_desc:'Subsidies for power tillers, weeders, paddy transplanters, and harvesting machines.',
    scheme_machinery_sub:'40%–70% Subsidy',
    scheme_tiller_loan:'Power Tiller Loan Scheme',
    scheme_tiller_loan_desc:'Available through cooperative agriculture banks.',
    scheme_tiller_loan_i1:'Up to 90% of the cost financed through loans.',
    scheme_equipment:'Agricultural Equipment Subsidy',
    scheme_equipment_desc:'Subsidies for plant protection tools and farm equipment (e.g., for pulses).',
    scheme_equipment_sub:'50% Subsidy',
    scheme_pumpset:'Pump Set Subsidy',
    scheme_pumpset_desc:'Subsidized electric pump sets for irrigation.',
    scheme_pumpset_i1:'Around 40% subsidy for pump sets.',
    scheme_pumpset_i2:'Higher subsidy for small farmers and SC/ST farmers.',
    scheme_value_addition:'Value-Addition Scheme',
    scheme_value_addition_desc:'Support for starting processing units for crops like tomato puree, turmeric powder, and banana processing.',
    scheme_value_addition_sub:'25% Investment Subsidy (up to ₹1.5 crore)',
    scheme_micro_irrigation:'Micro Irrigation Scheme (Tamil Nadu)',
    scheme_micro_irrigation_desc:'Subsidy for drip irrigation and sprinkler irrigation to save water and increase crop yield.',
    scheme_micro_irrigation_sub:'Up to 100% subsidy for small and marginal farmers',
    scheme_foundation_seeds:'Production of Foundation Seeds Scheme',
    scheme_foundation_seeds_desc:'Improve quality seeds for crops like pulses.',
    scheme_foundation_seeds_sub:'₹1000 subsidy per quintal',
    scheme_kalaignar_village:'Kalaignarin All Village Integrated Agricultural Development Programme',
    scheme_kalaignar_village_desc:'Financial support for village-level agriculture development.',
    scheme_kalaignar_village_i1:'Irrigation improvements',
    scheme_kalaignar_village_i2:'Crop diversification',
    scheme_kalaignar_village_i3:'Farm infrastructure',
    scheme_mannuyir_kaathu:'Mannuyir Kaathu Mannuyir Kaapom Scheme',
    scheme_mannuyir_kaathu_desc:'Promotes organic farming and soil protection.',
    scheme_mannuyir_kaathu_i1:'Soil health improvement',
    scheme_mannuyir_kaathu_i2:'Sustainable agriculture support',
    /* dashboard */
    revenue:'Revenue', avg_rating:'Avg Rating',
    recent_orders:'Recent Orders', all_orders:'All Orders',
    customer:'Customer', amount:'Amount', action:'Action',
    items:'Items', delivery:'Delivery',
    customer_reviews:'Customer Reviews',
    farm_profile:'Farm Profile', mobile:'Mobile', about_farm:'About Your Farm',
    tamil_name:'Tamil Name', unit:'Unit', kg:'Kilogram (kg)',
    per_unit_piece:'Per Unit / Piece', per_bunch:'Per Bunch', per_litre:'Per Litre',
    price_history:'Price History',
    customer_details:'Customer Details', customer_contact:'Customer Contact',
    delivery_addr:'Delivery Address', mobile_no:'Phone',
    order_info:'Order Info', order_date:'Order Date', payment:'Payment', method:'Method',
    view_info:'View Info',
    no_orders:'No orders found',
    no_farmers:'No farmers registered yet',
    no_market_data:'No market price data available',
    no_products_yet:'No products yet. Click "Add Product" to get started!',
    failed_products:'Failed to load products',
    no_reviews:'No reviews yet',
    failed_load:'Failed to load',
    completed:'Completed',
    pending:'Pending',
    order_status_updated:'Order status updated',
    product_updated:'Product updated!',
    product_added:'Product added! 🌾',
    fill_required:'Fill all required fields',
    delete_confirm:'Delete this product?',
    product_deleted:'Product deleted',
    /* reviews */
    write_review:'Write a Review', quality:'Product Quality',
    del_time:'Delivery Time', overall:'Overall Service',
    submit_review:'Submit Review',
    /* market */
    market_title:'Current Market Prices',
    market_location:'Market/Location',
    market_sub:'Compare farmer prices with market rates',
    last_updated:'Last updated',
    /* misc */
    loading:'Loading…', save:'Save', cancel:'Cancel',
    edit:'Edit', delete:'Delete', confirm:'Confirm', close:'Close',
    back:'Back', next:'Next', submit:'Submit',
    filter:'Filter', apply:'Apply Filters', clear:'Clear',
    price_range:'Price Range', sort_by:'Sort By',
    footer_tag:'Connecting farmers directly with customers across Tamil Nadu.',
    footer_links:'Quick Links', footer_cats:'Categories', footer_support:'Support',
    footer_rights:'All rights reserved.',
    filter_location:'District:',
    all_locations:'All Districts',
    join_agridirect:'Join AgriDirect',
    cta_h2:'Start Buying or Selling Fresh Produce',
    cta_p:'Join thousands of farmers and customers already on AgriDirect. No fees to start.',
    join_farmer:'Join as Farmer', start_shopping:'Start Shopping',
  },

  ta: {
    site_title:'AgriDirect — வயலிலிருந்து மேசை வரை',
    nav_home:'முகப்பு', nav_products:'பொருட்கள்', nav_farmers:'விவசாயிகள்',
    nav_market:'சந்தை விலைகள்', nav_cart:'கார்ட்',
    nav_login:'உள்நுழை', nav_register:'பதிவு செய்',
    nav_dashboard:'டாஷ்போர்டு', nav_logout:'வெளியேறு',
    nav_home:'முகப்பு', nav_orders:'ஆர்டர்கள்', nav_reviews:'மதிப்பாய்வுகள்', nav_profile:'சுயவிவரம்',
    search_ph:'காய்கறிகள், பழங்கள், தானியங்கள் தேடுங்கள்…',
    hero_eyebrow:'நேரடியாக வயலிலிருந்து',
    hero_h1a:'நேரடியாக வாங்குங்கள்', hero_h1b:'உள்ளூர் விவசாயிகளிடம்',
    hero_sub:'நியாயமான விலையில் மிகவும் புதுமையான பொருட்களை பெறுங்கள்.',
    hero_shop:'இப்போதே வாங்கவும்', hero_farmer:'நான் ஒரு விவசாயி',
    hero_stat_farmers:'விவசாயிகள்', hero_stat_products:'பொருட்கள்',
    hero_stat_orders:'ஆர்டர்கள்', hero_stat_cities:'நகரங்கள்',
    cat_heading:'வகையின்படி வாங்கவும்',
    cat_all:'அனைத்தும்', cat_vegetables:'காய்கறிகள்', cat_fruits:'பழங்கள்',
    cat_grains:'தானியங்கள்', cat_dairy:'பால் பொருட்கள்',
    featured:'சிறப்பு பொருட்கள்', see_all:'அனைத்தையும் காண் →',
    add_to_cart:'கார்ட்டில் சேர்', added:'சேர்க்கப்பட்டது!',
    market_price:'சந்தை விலை', per_kg:'/கிலோ', per_unit:'/அலகு', per_litre:'/லிட்டர்',
    organic:'இயற்கை', inorganic:'வழக்கமான',
    harvest_date:'அறுவடை நாள்', in_stock:'கையிருப்பு உள்ளது', out_of_stock:'கையிருப்பில் இல்லை',
    available:'கிடைக்கும்',
    no_results:'பொருட்கள் இல்லை', no_results_sub:'வடிப்பான்களை மாற்றி முயற்சிக்கவும்.',
    login:'உள்நுழை', register:'பதிவு செய்',
    mobile_no:'மொபைல் எண்', otp:'OTP உள்ளிடவும்',
    otp_sent:'OTP அனுப்பப்பட்டது', verify:'OTP சரிபார்',
    resend:'OTP மீண்டும் அனுப்பு', resend_in:'மீண்டும் அனுப்பு', seconds:'வி',
    full_name:'முழு பெயர்', i_am_farmer:'நான் ஒரு விவசாயி',
    i_am_customer:'நான் ஒரு வாடிக்கையாளர்',
    location:'இடம் / கிராமம்', farm_name:'பண்ணை பெயர்',
    continue_btn:'தொடரவும்',
    add_profile_photo:'சுயவிவரப் புகைப்படத்தைச் சேர்க்கவும்',
    cart_title:'உங்கள் கார்ட்', cart_empty:'கார்ட் காலியாக உள்ளது',
    cart_empty_sub:'சில பொருட்களை சேர்க்கவும்!',
    subtotal:'மொத்தம்', delivery:'டெலிவரி', free:'இலவசம்', total:'மொத்த தொகை',
    go_checkout:'கட்டணம் செலுத்தவும்',
    checkout_title:'கட்டணம் செலுத்துதல்',
    delivery_addr:'டெலிவரி முகவரி', delivery_method:'டெலிவரி முறை',
    payment_method:'கட்டண முறை',
    cod:'பணம் டெலிவரியில்', cod_desc:'ஆர்டர் வந்தபின் பணம் செலுத்தவும்',
    online_pay:'ஆன்லைன் கட்டணம்', online_desc:'UPI, கார்டுகள், நெட் பேங்கிங்',
    farmer_del:'விவசாயி டெலிவரி', local_del:'உள்ளூர் டெலிவரி',
    farm_pickup:'பண்ணையிலிருந்து எடுக்கவும்',
    place_order:'ஆர்டர் செய்யவும்', order_success:'ஆர்டர் வெற்றிகரமாக செய்யப்பட்டது!',
    addr_line1:'முகவரி வரி 1', addr_line2:'முகவரி வரி 2 (விருப்பமானது)',
    city:'நகரம்', state:'மாநிலம்', pincode:'பின்கோடு',
    my_orders:'என் ஆர்டர்கள்', order_id:'ஆர்டர் ஐடி', order_date:'தேதி',
    order_status:'நிலை', order_total:'மொத்தம்',
    track_order:'கண்காணிக்கவும்',
    status_placed:'ஆர்டர் செய்யப்பட்டது', status_confirmed:'உறுதிப்படுத்தப்பட்டது',
    status_out:'டெலிவரியில் உள்ளது', status_out_for_delivery:'டெலிவரியில் உள்ளது', status_delivered:'டெலிவர் செய்யப்பட்டது', status_cancelled:'ரத்து செய்யப்பட்டது',
    method_pickup:'பண்ணையில் வாங்குதல்', method_delivery:'வீட்டுக்கே டெலிவரி',
    method_home_delivery:'வீட்டுக்கே டெலிவரி',
    method_farmer_delivery:'விவசாயி டெலிவரி', method_local_partner:'உள்ளூர் டெலிவரி', method_farm_pickup:'பண்ணையில் வாங்குதல்',
    dashboard:'டாஷ்போர்டு', my_products:'என் பொருட்கள்',
    add_product:'பொருள் சேர்க்கவும்', edit_product:'திருத்து',
    del_product:'நீக்கு', save_product:'பொருளை சேமிக்கவும்',
    update_product:'புதுப்பிக்கவும்',
    product_name:'பொருளின் பெயர்', category:'வகை',
    price_per:'கிலோ / அலகுக்கான விலை', qty:'கிடைக்கும் அளவு',
    product_type:'பொருளின் வகை', description:'விவரம்',
    upload_imgs:'படங்களை பதிவேற்றவும்',
    price_changed:'விலை புதுப்பிக்கப்பட்டது',
    price_change_alert:'முழுமையான வெளிப்படைத்தன்மைக்காக விலை மாற்றம் தேதி மற்றும் நேரத்துடன் பதிவு செய்யப்படும்.',
    click_to_upload:'பல படங்களை பதிவேற்ற கிளிக் செய்யவும்',
    drag_drop:'அல்லது இழுத்து விடவும்',
    img_hint:'JPG, PNG, WEBP • அதிகபட்சம் 5 படங்கள் • ஒவ்வொன்றும் அதிகபட்சம் 5 MB',
    use_camera:'கேமராவைப் பயன்படுத்தவும்',
    upload_hint:'புத்துணர்ச்சி மற்றும் தரத்தைக் காட்டும் தெளிவான, வெளிச்சமான புகைப்படங்களைப் பதிவேற்றவும்',
    farmer_support:'விவசாயி ஆதரவு',
    tn_gov_schemes:'தமிழக அரசுத் திட்டங்கள் மற்றும் ஆதரவு',
    scheme_electricity:'விவசாய பம்புகளுக்கு இலவச மின்சாரம்',
    scheme_electricity_desc:'தமிழக விவசாயிகளுக்கு விவசாயத்திற்காக பயன்படுத்தப்படும் பம்ப்செட்டுகளுக்கு இலவச மின்சாரம் வழங்கப்படுகிறது.',
    scheme_electricity_i1:'விவசாய பம்புகளுக்கான மின்சாரம் இலவசம்.',
    scheme_electricity_i2:'உள்கட்டமைப்பு வசதிகளின் அடிப்படையில் புதிய இணைப்புகள் வழங்கப்படுகின்றன.',
    scheme_electricity_i3:'சூரிய சக்தி பம்புகளைப் பயன்படுத்தும் விவசாயிகளுக்கு சில விதிகளின் கீழ் புதிய இலவச இணைப்புகள் கிடைக்காமல் போகலாம்.',
    scheme_machinery:'விவசாய இயந்திரங்கள் மானியம்',
    scheme_machinery_desc:'பவர் டில்லர், களை எடுக்கும் இயந்திரம், நெல் நடவு இயந்திரம் மற்றும் அறுவடை இயந்திரங்களுக்கு மானியம்.',
    scheme_machinery_sub:'40%–70% மானியம்',
    scheme_tiller_loan:'பவர் டில்லர் கடன் திட்டம்',
    scheme_tiller_loan_desc:'கூட்டுறவு வேளாண்மை வங்கிகள் மூலம் கிடைக்கும்.',
    scheme_tiller_loan_i1:'பவர் டில்லர் விலையில் 90% வரை கடனாகப் பெறலாம்.',
    scheme_equipment:'விவசாய உபகரணங்கள் மானியம்',
    scheme_equipment_desc:'பயிர்ப் பாதுகாப்பு கருவிகள் மற்றும் பண்ணை உபகரணங்களுக்கு மானியம் (எ.கா: பருப்பு வகைகள்).',
    scheme_equipment_sub:'50% மானியம்',
    scheme_pumpset:'பம்ப்செட் மானியம்',
    scheme_pumpset_desc:'நீர்ப்பாசனத்திற்காக மானிய விலையில் மின்சார பம்ப்செட்டுகள்.',
    scheme_pumpset_i1:'பம்ப்செட்டுகளுக்கு சுமார் 40% மானியம்.',
    scheme_pumpset_i2:'சிறு விவசாயிகள் மற்றும் SC/ST விவசாயிகளுக்கு கூடுதல் மானியம்.',
    scheme_value_addition:'மதிப்பு கூட்டப்பட்ட உற்பத்தித் திட்டம்',
    scheme_value_addition_desc:'தக்காளி கூழ், மஞ்சள் தூள் மற்றும் வாழை பதப்படுத்துதல் போன்ற அலகுகளைத் தொடங்க ஆதரவு.',
    scheme_value_addition_sub:'25% முதலீட்டு மானியம் (₹1.5 கோடி வரை)',
    scheme_micro_irrigation:'நுண்ணீர் பாசனத் திட்டம் (தமிழ்நாடு)',
    scheme_micro_irrigation_desc:'நீர் சேமிப்பு மற்றும் பயிர் விளைச்சலை அதிகரிக்க சொட்டு நீர் மற்றும் தெளிப்பு நீர் பாசனத்திற்கு மானியம்.',
    scheme_micro_irrigation_sub:'சிறு மற்றும் குறு விவசாயிகளுக்கு 100% வரை மானியம்',
    scheme_foundation_seeds:'ஆதார விதைகள் உற்பத்தித் திட்டம்',
    scheme_foundation_seeds_desc:'பருப்பு வகைகள் போன்ற பயிர்களுக்கு தரமான விதைகளை மேம்படுத்துதல்.',
    scheme_foundation_seeds_sub:'குவிண்டாலுக்கு ₹1000 மானியம்',
    scheme_kalaignar_village:'கலைஞரின் அனைத்து கிராம ஒருங்கிணைந்த வேளாண் வளர்ச்சித் திட்டம்',
    scheme_kalaignar_village_desc:'கிராம அளவிலான வேளாண் வளர்ச்சிக்கு நிதி உதவி.',
    scheme_kalaignar_village_i1:'நீர்ப்பாசன மேம்பாடுகள்',
    scheme_kalaignar_village_i2:'பயிர் பல்வகைப்படுத்தல்',
    scheme_kalaignar_village_i3:'பண்ணை உள்கட்டமைப்பு',
    scheme_mannuyir_kaathu:'மண்ணுயிர் காத்து மண்ணுயிர் காப்போம் திட்டம்',
    scheme_mannuyir_kaathu_desc:'இயற்கை விவசாயம் மற்றும் மண் பாதுகாப்பை ஊக்குவிக்கிறது.',
    scheme_mannuyir_kaathu_i1:'மண் ஆரோக்கியம் மேம்படுத்துதல்',
    scheme_mannuyir_kaathu_i2:'நிலையான விவசாய ஆதரவு',
    /* dashboard */
    revenue:'வருவாய்', avg_rating:'சராசரி மதிப்பீடு',
    recent_orders:'சமீபத்திய ஆர்டர்கள்', all_orders:'அனைத்து ஆர்டர்கள்',
    customer:'வாடிக்கையாளர்', amount:'தொகை', action:'நடவடிக்கை',
    items:'பொருட்கள்', delivery:'டெலிவரி',
    customer_reviews:'வாடிக்கையாளர் மதிப்பாய்வுகள்',
    farm_profile:'பண்ணை சுயவிவரம்', mobile:'மொபைல்', about_farm:'உங்கள் பண்ணை பற்றி',
    tamil_name:'தமிழ் பெயர்', unit:'அலகு', kg:'கிலோகிராம் (கிலோ)',
    per_unit_piece:'ஒரு அலகு / துண்டு', per_bunch:'ஒரு கட்டு', per_litre:'ஒரு லிட்டர்',
    price_history:'விலை வரலாறு',
    customer_details:'வாடிக்கையாளர் விவரங்கள்', customer_contact:'வாடிக்கையாளர் தொடர்பு',
    delivery_addr:'டெலிவரி முகவரி', mobile_no:'தொலைபேசி',
    order_info:'ஆர்டர் விவரம்', order_date:'ஆர்டர் தேதி', payment:'கட்டணம்', method:'முறை',
    view_info:'தகவலைக் காண்',
    no_orders:'ஆர்டர்கள் எதுவும் இல்லை',
    no_farmers:'விவசாயிகள் யாரும் பதிவு செய்யப்படவில்லை',
    no_market_data:'சந்தை விலை தரவு இல்லை',
    no_products_yet:'பொருட்கள் எதுவும் இல்லை. தொடங்க "பொருள் சேர்க்கவும்" என்பதைக் கிளிக் செய்யவும்!',
    failed_products:'பொருட்களை ஏற்றுவதில் தோல்வி',
    no_reviews:'மதிப்பாய்வுகள் எதுவும் இல்லை',
    failed_load:'ஏற்றுவதில் தோல்வி',
    completed:'முடிந்தது',
    pending:'நிலுவையில் உள்ளது',
    order_status_updated:'ஆர்டர் நிலை புதுப்பிக்கப்பட்டது',
    product_updated:'பொருள் புதுப்பிக்கப்பட்டது!',
    product_added:'பொருள் சேர்க்கப்பட்டது! 🌾',
    fill_required:'அனைத்து கட்டாய புலங்களையும் நிரப்பவும்',
    delete_confirm:'இந்த பொருளை நீக்கவா?',
    product_deleted:'பொருள் நீக்கப்பட்டது',
    /* reviews */
    write_review:'மதிப்பாய்வு எழுதவும்', quality:'பொருளின் தரம்',
    del_time:'டெலிவரி நேரம்', overall:'மொத்த சேவை',
    submit_review:'சமர்ப்பிக்கவும்',
    market_title:'தற்போதைய சந்தை விலைகள்',
    market_location:'சந்தை / இடம்',
    market_sub:'விவசாயி விலைகளை சந்தை விலைகளுடன் ஒப்பிடவும்',
    last_updated:'கடைசி புதுப்பிப்பு',
    loading:'ஏற்றுகிறது…', save:'சேமி', cancel:'ரத்து',
    edit:'திருத்து', delete:'நீக்கு', confirm:'உறுதி', close:'மூடு',
    back:'திரும்பு', next:'அடுத்து', submit:'சமர்ப்பி',
    filter:'வடிகட்டு', apply:'பயன்படுத்து', clear:'அழி',
    price_range:'விலை வரம்பு', sort_by:'வரிசைப்படுத்து',
    footer_tag:'தமிழ்நாடு முழுவதும் விவசாயிகளை நேரடியாக வாடிக்கையாளர்களுடன் இணைக்கிறோம்.',
    footer_links:'விரைவு இணைப்புகள்', footer_cats:'வகைகள்', footer_support:'ஆதரவு',
    footer_rights:'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    filter_location:'மாவட்டம்:',
    all_locations:'அனைத்து மாவட்டங்கள்',
    join_agridirect:'அக்ரிடைரக்டில் சேருங்கள்',
    cta_h2:'புதிய விளைபொருட்களை வாங்க அல்லது விற்கத் தொடங்குங்கள்',
    cta_p:'ஏற்கனவே அக்ரிடைரக்டில் உள்ள ஆயிரக்கணக்கான விவசாயிகள் மற்றும் வாடிக்கையாளர்களுடன் இணையுங்கள். தொடங்குவதற்கு கட்டணம் ஏதுமில்லை.',
    join_farmer:'விவசாயியாக சேர', start_shopping:'வாங்க தொடங்கு',
  }
};

/* Active language – persisted in localStorage */
let currentLang = localStorage.getItem('agri_lang') || 'en';

/** Translate a key */
function t(key) {
  return (LANG[currentLang] && LANG[currentLang][key])
      || (LANG.en && LANG.en[key])
      || key;
}

/** Switch language and re-render all tagged elements */
function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('agri_lang', lang);
  document.documentElement.lang = lang;
  document.body.classList.toggle('lang-ta', lang === 'ta');

  /* text content */
  document.querySelectorAll('[data-i18n]').forEach(el => {
    el.textContent = t(el.dataset.i18n);
  });
  /* placeholders */
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    el.placeholder = t(el.dataset.i18nPh);
  });
  /* title */
  document.title = t('site_title');

  /* toggle lang buttons */
  document.querySelectorAll('.lang-btn').forEach(btn => btn.classList.remove('active'));
  document.getElementById('lang-' + lang)?.classList.add('active');
}

/** Helper to re-translate all data-i18n elements on the current page */
function translatePage() {
  setLanguage(currentLang);
}

/* Run on page load */
document.addEventListener('DOMContentLoaded', () => setLanguage(currentLang));
